routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix'=>''], function(){
    Route::resource('groups', 'GroupController');
});

Route::group(['prefix'=>''], function(){
    Route::resource('groups.students', 'StudentController');
});


Route::get('/', function () {
    return view('welcome');})->name('start.index');

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Group extends Model
{
    protected $fillable = ['title','description'];

    public function students()
    {
        return $this->hasMany(Student::class);
    }

}

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Student extends Model
{
    protected $guarded = [];
    protected $primaryKey = 'id';
    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    public function subjects()
    {
        return $this->belongsToMany(Subject::class);
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Models\Group;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

       return view ('groups.index',[
           'groups' => Group::paginate(10),
           ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

            return view('groups.create',[
            'group'=>[],

        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(),
            ['title' => 'required',
                'description'=>'required'
            ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withInput();
        }
        $group = Group::create($request->all());
        return redirect()->route('groups.index',$group);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function show(Group $group)
    {
        return view ('groups.show',['group'=>$group]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function edit(Group $group)
    {

        return view('groups.edit',[
            'group' => $group
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Group $group)
    {
        $validator = Validator::make(
            $request->all(),
            ['title' => 'required',
                'description'=>'required'
            ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withInput();
        }
        $group->update($request->all());
        return redirect()->route('groups.show', $group);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function destroy(Group $group)
    {
        $group->delete();
        return redirect()->route('groups.index');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Group;
use App\Models\Student;
use App\Models\Subject;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($group_id)
    {

    return view ('groups.students.create',[
        'groups'=>$group_id,
        'student'=>[],
        'subjects'=>Subject::get()
    ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
        $request->all(),
        ['name' => 'required',
            'birthday'=>'required'
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withInput();
        }

        $student = Student::create($request->all());
        if($request->input('subjects')):
        $student->subjects()->attach($request->input('subjects'));
        endif;
        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $group_id, $student_id)
    {
        $groups=$group_id;
        $student = Student::find($student_id);
        return view ('groups.students.edit')->with('student',$student)->with('groups',$groups);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Group $group, Student $student)
    {
        $validator = Validator::make(
            $request->all(),
            ['name' => 'required',
                'birthday'=>'required'
            ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withInput();
        }
        $student->update($request->all());
        return redirect()->route('groups.index', $student);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Group $group, Student $student)

    {  
        $student->delete();
        return redirect()->back();
    }
}

resources/views/groups/students/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Добавление студента</h2>
        <ol class="breadcrumb">
            <li class="active">Добавить</li>
        </ol>

        <hr />
        <form class="form-horizontal" action="{{route('groups.students.store',[$groups])}}" method="post">
            <input type="hidden" name="group_id" value="{{$groups}}">
            {{csrf_field()}}
            <div class="form-group"><label class="col-sm-2 control-label">Предметы:</label>
                <div class="col-sm-10">
                    @foreach($subjects as $subject)
                    <input type="hidden" name="subjects[]" value="{{$subject->id}}">
                      @endforeach
                </div>
            </div>


            <label for="">ФИО студента</label>
            <input type="text" class="form-control" name="name" placeholder="Фамилия Имя Отчество">
            <label for="">Дата рождения</label>
            <input type="text" class="form-control" name="birthday"  placeholder="Дата рождения">
            <hr />
            <input class="btn btn-primary" type="submit" value="Добавить">
        </form>


    </div>
@endsection

resources/views/groups/students/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Редактирование студента</h2>
        <ol class="breadcrumb">
            <li><a href="{{route('groups.index')}}">Студенты</a></li>
            <li class="active">Редактировать</li>
        </ol>

        <hr />

        <form class="form-horizontal" action="{{route('groups.students.update',[$groups, $student])}}" method="post">
            <input type="hidden" name="_method" value="put">
            {{csrf_field()}}

            <label for="">ФИО</label>
            <input type="text" class="form-control" name="name" placeholder={{$student->name}}>
            <label for="">Дата рождения</label>
            <input type="text" class="form-control" name="birthday" placeholder={{$student->birthday}} >
            <hr />
            <input class="btn btn-primary" type="submit" value="Изменить">
        </form>

    </div>
@endsection

resources/views/groups/students/index.blade.php
@extends('layouts.app')


@section('content')

    <div class="container">

        <h2>Список студентов</h2>
        <ol class="breadcrumb">
            <li><a href="{{route('groups.index')}}">Группы</a></li>
            <li class="active">Студенты</li>
        </ol>

        <hr>

        <a href="{{route('students.create')}}" class="btn btn-primary pull-right">Добавить студента</a>
        <table class = "table table-striped">
            <thead>
            <th>Название группы</th>
            <th>ФИО студента</th>
            <th>Дата рождения</th>
            <th class="text-right">Редактировать</th>
            <th class="text-right">Удалить</th>
            </thead>
            <tbody>

             @forelse ($students as $student)
                <tr>
                    <td>{{$student->title}}</td>
                    <td>{{$student->name}}</td>
                    <td>{{$student->birthday}}</td>

                    <td class="text-right">
                        <a class="btn btn-default" href="{{route('students.edit', $student)}}"><i class="fa
                     fa-edit"></i></a>
                    </td>

                    <td class="text-right">
                        <form onsubmit="if(confirm('Удалить?')){return true}else{return false}" action="{{route('students.destroy',$student)}}" method="post">
                            <input type="hidden" name="_method" value="delete">
                            {{csrf_field()}}

                            <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                @endempty

            </tbody>
        </table>
    </div>
@endsection