routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix'=>''], function(){
    Route::resource('groups', 'GroupController');
});

Route::group(['prefix'=>''], function(){
    Route::resource('groups.students', 'StudentController');
});


Route::get('/', function () {
    return view('welcome');})->name('start.index');

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Group extends Model
{
    protected $fillable = ['title','description'];

    public function students()
    {
        return $this->hasMany(Student::class);
    }

}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Models\Group;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

       return view ('groups.index',[
           'groups' => Group::paginate(10),
           ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

            return view('groups.create',[
            'group'=>[],

        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(),
            ['title' => 'required',
                'description'=>'required'
            ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withInput();
        }
        $group = Group::create($request->all());
        return redirect()->route('groups.index',$group);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function show(Group $group)
    {
        return view ('groups.show',['group'=>$group]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function edit(Group $group)
    {

        return view('groups.edit',[
            'group' => $group
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Group $group)
    {
        $validator = Validator::make(
            $request->all(),
            ['title' => 'required',
                'description'=>'required'
            ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withInput();
        }
        $group->update($request->all());
        return redirect()->route('groups.show', $group);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function destroy(Group $group)
    {
        $group->delete();
        return redirect()->route('groups.index');
    }
}

resources/views/groups/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Создание группы</h2>
        <ol class="breadcrumb">
            <li><a href="{{route('groups.index')}}">Группы</a></li>
            <li class="active">Создать</li>
        </ol>

        <hr />
        <form class="form-horizontal" action="{{route('groups.store')}}" method="post">
            {{csrf_field()}}
        <label for="">Название группы</label>
            <input type="text" class="form-control" name="title" placeholder="Название группы">
        <label for="">Описание</label>
            <input type="text" class="form-control" name="description" placeholder="Описание">
        <hr />
            <input class="btn btn primary" type="submit" value="Добавить">
        </form>

    </div>
@endsection

resources/views/groups/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Редактирование группы</h2>
        <ol class="breadcrumb">
            <li><a href="{{route('groups.index')}}">Группы</a></li>
            <li class="active">Редактировать</li>
        </ol>

        <hr />

        <form class="form-horizontal" action="{{route('groups.update',$group)}}" method="post">
            <input type="hidden" name="_method" value="put">
            {{csrf_field()}}


            <label for="">Новое название группы</label>
            <input type="text" class="form-control" name="title" placeholder="{{$group->title}}">
            <label for="">Новое описание</label>
            <input type="text" class="form-control" name="description" placeholder={{$group->description}}>
            <hr />
            <input class="btn btn primary" type="submit" value="Изменить">
        </form>

    </div>
@endsection

resources/views/groups/index.blade.php
@extends('layouts.app')


@section('content')

    <div class="container">


        <h2>Список групп</h2>
        <ol class="breadcrumb">
            <li><a href="{{route('start.index')}}">Главная</a></li>
            <li class="active">Группы</li>
        </ol>

        <hr>


        <table class = "table table-striped">
            <thead>
            <th>Название группы</th>
            <th>Описание</th>
            <th class="text-right">Просмотр</th>
            <th class="text-right">Редактировать</th>
            <th class="text-right">Удалить</th>
            </thead>
            <tbody>
            @forelse ($groups as $group)
                <tr>
                    <td class="text-left"> {{$group->title}}</td>
                    <td>{{$group->description}}</td>

                    <td class="text-right">
                        <a class="btn btn-default" href="{{route('groups.show', $group)}}"><i class="fa
                     fa-th-list"></i></a>
                    </td>

                    <td class="text-right">
                        <a class="btn btn-default" href="{{route('groups.edit', $group)}}"><i class="fa
                     fa-edit"></i></a>
                    </td>

                    <td class="text-right">
                        <form onsubmit="if(confirm('Удалить?')){return true}else{return false}" action="{{route('groups.destroy',$group)}}" method="post">
                            <input type="hidden" name="_method" value="delete">
                            {{csrf_field()}}

                            <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
            @endempty
            </tbody>
        </table>
        <hr />
        <a href="{{route('groups.create')}}" class="btn btn-primary pull-right">Создать группу</a>
    </div>
@endsection

resources/views/groups/show.blade.php
@extends('layouts.app')


@section('content')

    <div class="container">

        <h2>Список студентов</h2>
        <ol class="breadcrumb">
            <li><a href="{{route('groups.index')}}">Группы</a></li>
            <li class="active">Студенты</li>
        </ol>

        <hr>

        <table class = "table table-striped">
            <h1 class="text-center">{{$group->title}}</h1>
            <p class="text-center">{{$group->description}}</p>
            <thead>
            <th>ФИО студента</th>
            <th>Дата рождения</th>
            <th class="text-center">Русский язык</th>
            <th class="text-center">Математика</th>
            <th class="text-center">История</th>
            <th class="text-right">Редактировать</th>
            <th class="text-right">Удалить</th>
            </thead>
            <tbody>
            @forelse($group->students as $student)
                <tr>

                    <td>{{$student->name}}</td>
                    <td>{{$student->birthday}}</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="text-right">
                        <a class="btn btn-default" href="{{route('groups.students.edit',[$group->id, $student->id])}}"><i class="fa
                     fa-edit"></i></a>
                    </td>
                    <td class="text-right">
                        <form onsubmit="if(confirm('Удалить?')){return true}else{return false}" action="{{route('groups.students.destroy',[$group->id, $student])}}" method="post">
                            <input type="hidden" name="_method" value="delete">
                            {{csrf_field()}}
                            <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                <td></td>
                    <td></td>
                    <td><h3 class="text-center">Студентов нет</h3></td>
                    <td class="text-right"></td>
                    <td class="text-right"></td>
                </tr>
            @endforelse
            </tbody>
        </table>
        <hr />
         <a href="{{route('groups.students.create', [$group->id])}}" class="btn btn-primary pull-right">Добавить студента</a>
    </div>

@endsection